### PR TITLE
Add underlying.getClass().getClassLoader() as fallback

### PR DESCRIPTION
**Pull request by felixbarny**
I currently have the problem that I get a `ClassNotFoundException` when `Enhance#.create()` is called, because non of the current candidate class loaders can load the `Statement` interface provided by the mysql connector. This is because the mysql connector is included in an Eclipse RCP plug-in OSGi bundle and the bundle which contains P6Spy does not have a dependency on it. I can't simply depend on the MySql plug-in as this would introduce a cyclic dependency.

```
Plug-In containing MySql --depends on--> Plug-In containing P6Spy
```

Adding the underlying class' class loader to the list of candidate classloaders fixes this problem. Also, this pull request fixes the ` TODO refactor - to get rid of endless try - catch`.

### CODE REVIEW

**Comment by felixbarny** [comment]
See also #286 

This pull requests basically implements this:

> We had a similar issue with glassfish on #188. For that one, we just specified the classloader to use. Perhaps the better solution would be to use the classloader which loaded the object being proxied

**Comment by typekpb** [comment]
Seems OK from my point of view. 
Would love to see the integration tests (https://github.com/p6spy/p6spy-it) having this fix in, prior to releasing the new version (anyway, those didn't run for a longer time so could be nice to see the result).
@quintonm your opinion on this?

**Comment by felixbarny** [comment]
Do you mean a new integration test which specifically tests this issue? Might be difficult to do as this issue occurred in an Eclipse RCP application. Or do you just mean to test the change with the current integration tests?

I'm using https://nightli.es/ to execute my integration tests every day. Might also be useful for you.

**Comment by typekpb** [comment]
@felixbarny no need to write new test, just wanted to make sure our integration test suite can still run (on various app servers).
nightli.es ? thanks for the tip, didn't know that one (I might be just too paranoid seeing all the permissions it asks for).

**Comment by felixbarny** [comment]
Actually nightli.es asks for the same permissions as Travis CI. But I also hate it if applications request too much permissions. Versioneye really went mad. They now request **read and write all public and private repository data**. No way I'm going to accept that! Originally, they only wanted to have read access to the email address.

**Comment by quintonm** [comment]
@typekpb I think that we should merge and then run the integration tests.  If a problem is found then we could rollback the change.

**Comment by typekpb** [comment]
Exactly!

**Pull request merged**
