### PR TITLE
Optionally measure time with System.nanoTime()

### LINKED ISSUE #295: Add option to report execution time less than 1 ms
When using P6Spy with embedded databases, the execution time is normally reported as 0 ms.

### PR DESCRIPTION
**Pull request by felixbarny**
(closes #295)

### CODE REVIEW

**Comment by quintonm** [comment]
The PR looks great!  Any chance you could add a few tests?

**Comment by typekpb** [comment]
And docs as well? Btw. I guess @felixbarny is a perfect candidate for admin
access to this repo.

The PR looks great! Any chance you could add a few tests?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/p6spy/p6spy/pull/316#issuecomment-216923644>

**Comment by felixbarny** [comment]
Sure! Just wanted to get sure you are in line with the general direction before puttung too much effort in it.

**Comment by felixbarny** [comment]
Do you think the tests are ok?

**Comment by quintonm** [comment]
Looks good to me.

**Comment by typekpb** [comment]
good job! would be nice to update also:
* `src/main/assembly/individualFiles/spy.properties` - as I'd expect people to take this one as a initial template
* `src/site/markdown/2.0/configandusage.md` - to document the flag
* `src/test/java/com/p6spy/engine/spy/option/P6TestOptionDefaults.java` to reflect default value for a flag

**Comment by felixbarny** [comment]
Thx! Done.

**Comment by quintonm** [comment]
The additional docs look good.  Great work on this PR!

+1 for merge

**Comment by felixbarny** [comment]
Great, thx a lot! @typekpb if it looks good to you as well I think you can merge this. Is there some kind of process who merges the pull requests and how many members have to agree on a change?

**Comment by typekpb** [comment]
@felixbarny well done!

merge process? I don't think so, the only one we used to follow was that @quintonm is the gatekeeper :) as he's got the deepest knowhow in the area

**Comment by typekpb** [comment]
@felixbarny I'd be happy to see the process in place, feel free to suggest one

**Comment by felixbarny** [comment]
I don't think that a strict process is needed. I agree that at least @quintonm should review a pull request and optionally ask for another opinion. Then it should be merged by either quinton or the other reviewer.

**Pull request merged**
