### PR TITLE
[RFC] readthedocs.org and coveralls.io introduced

### PR DESCRIPTION
**Pull request by typekpb**
Please note: don't merge until there is a common agreement on taking this path in our docs.
Feedback welcome!

### CODE REVIEW

**Comment by typekpb** [comment]
@quintonm @felixbarny changes done, I'd need your feedback guys

**Comment by quintonm** [comment]
LGTM

**Comment by felixbarny** [comment]
LGTM

**Comment by felixbarny** [comment]
Merge comflicts need to be resolved

**Pull request merged**
