### PR TITLE
Add ability to register custom JdbcEventListenerFactory

### PR DESCRIPTION
**Pull request by felixbarny**

### CODE REVIEW

**Comment by felixbarny** [comment]
Hey @typekpb or @quintonm, would you mind a review? :)

I would be cool if we could a release after merging. @typekpb what is the release process again? Just adding a tag?

**Comment by gavlyukovskiy** [comment]
Didn't you think to make mechanism to create factory more friendly for non service loaders usage? I mean though module manager or something like this.
In my starter I set factory to `P6DataSource` directly when wrapping a data source so this change doesn't affect me, but still I don't think that `JdbcEventListenerFactoryLoader` should be responsible for creating default factory, it seems to me more like another way to create factory and giving it such responsibility feels wrong to me. @felixbarny WDYT?

**Comment by felixbarny** [comment]
Hi @gavlyukovskiy, thanks for your feedback. Well, there is already a option when you are not using a service loader - you can set the factory directly to the data source, which you seem to already do. The downside of this approach however is that the `jdbcEventListenerFactory` inside the `P6SpyDriver` might already be initialized by the framework, before you have a chance to set the factory manually.

That's why I created the `JdbcEventListenerFactoryLoader`. The service loader approach acts as a sort of callback for when the `jdbcEventListenerFactory` gets initialized. It offers you a way to set a custom factory. But if you don't register a custom factory, there has to be some kind of fallback. That's why the `JdbcEventListenerFactoryLoader` creates a `DefaultJdbcEventListenerFactory` in that case. Why shouldn't that be the responsibility of the `JdbcEventListenerFactoryLoader`?

**Comment by typekpb** [comment]
> I would be cool if we could a release after merging. @typekpb what is the release process again? Just adding a tag?

see: http://p6spy.readthedocs.io/en/latest/development.html#releasing-the-version

**Comment by felixbarny** [comment]
This PR is actually not about adding support for object pooling. It's just about having the ability not to use the `DefaultJdbcEventListenerFactory`.

**Comment by felixbarny** [comment]
If we want to document this, we actually also have to document how to register custom `JdbcEventListener`s, `P6Factories` and how to provide a custom `LoggingEventListener`. I'd add another section called "Advanced Integration" or sth like this.

But I feel this is a bit out of scope for this PR. Also, It would be really cool if we could merge and release this PR soon, as I need it for the upcoming alpha release of the Elastic APM Java agent.

**Comment by typekpb** [comment]
@felixbarny 3.7.0 released just now, should be in maven central soon.

**Comment by felixbarny** [comment]
thanks :)

**Pull request merged**
