### PR TITLE
fix: register passthru drivers on P6SpyDriver init (closes #348)

### LINKED ISSUE #348: tomcat 6x-8x integration
Once running (on https://github.com/p6spy/p6spy-it):

    export ORG_GRADLE_PROJECT_container=tomcat6x; ./gradlew clean unitTest 

I get Error:

		    Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.p6spy.engine.spy.impl.ContactRepository com.p6spy.engine.spy.impl.CrossRepoService.contactRepository; nested exception is
	 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [ApplicationContext.Driver.xml]: Invocation of init method failed; nested exception is liquibase.exc
	eption.DatabaseException: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:tcp://localhost:9091//home/pb/all/prg/oss/p6spy-it/build/h2/s1/test3)
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:508)
		at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
		... 46 more
	    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [ApplicationContext.Driver.xml]: Invocation of init method failed; nested exception is
	 liquibase.exception.DatabaseException: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:tcp://localhost:9091//home/pb/all/prg/oss/p6spy-it/build/
	h2/s1/test3)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
		at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:294)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1017)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
		... 48 more
	    Caused by: liquibase.exception.DatabaseException: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:tcp://localhost:9091//home/pb/all/prg/oss/p
	6spy-it/build/h2/s1/test3)
		at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:293)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
		... 60 more
	    Caused by: org.apache.tomcat.dbcp.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unable to find a driver that accepts jdbc:h2:tcp://localhost:9091//home/pb/all/prg/oss/p6spy-it/build/h2/s1/test3)
		at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
		at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
		at org.apache.tomcat.dbcp.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
		at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:288)
		... 62 more
	    Caused by: java.sql.SQLException: Unable to find a driver that accepts jdbc:h2:tcp://localhost:9091//home/pb/all/prg/oss/p6spy-it/build/h2/s1/test3
		at com.p6spy.engine.spy.P6SpyDriver.findPassthru(P6SpyDriver.java:115)
		at com.p6spy.engine.spy.P6SpyDriver.connect(P6SpyDriver.java:90)
		at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
		at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
		at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
		at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
		... 65 more

as described in our docs (http://p6spy.github.io/p6spy/2.0/install.html#tomcat), tomcat requires section similar to:

     driverlist=com.mysql.jdbc.Driver

I'm not sure about the cause, but do believe, that eager initialization of p6spy is missing here (https://github.com/p6spy/p6spy/commit/f4afcb362223af8c69aff75033e5c1787036b54b#diff-4b14eb1503c82de0bcf667723ff92964L59). There used to be in the `P6DataSource.java` following:

    static {
      // make sure that the core has been initialized
      P6Core.initialize();
    }

Do you guys have any idea how to proceed here?

I've tried adding some eager stuff into `P6DataSource.java`, namely:

      static {
		P6ModuleManager.getInstance();
	}

but that didn't help, so I'm starting to doubt I'm looking at a rigfht cause here.

### PR DESCRIPTION
**Pull request by typekpb**
I tested it locally, not sure about further impact.

We'd have public evidence for fix however only once this gets to release (rc3 maybe) and p6spy-it re-runs

### CODE REVIEW

**Comment by quintonm** [comment]
Will the integration tests not use the latest snapshot version?  I see that
the version for p6spy is set to latest.integration.

**Comment by typekpb** [comment]
Good question. I'm not sure to be honest. But unless you released rc2,
p6spy-it tests were failing.

**Comment by quintonm** [comment]
I built your branch and then ran the it tests locally for tomcat 6 and 7.
It looks like the lazy initialization was the source of the problem.

**Comment by typekpb** [comment]
@felixbarny thanks for suggestion, it worked! (I've tested the built jar locally with tomcat6)

**But** there is some interesting stuff I see, it's realted to: https://github.com/p6spy/p6spy-it/pull/19

If I want to test with p6spy-it I had to change from: `   p6spy: 'latest.integration',` to `p6spy: '3.0.0-SNAPSHOT',`.

Obviously gradle feels that  `3.0.0-SNAPSHOT` version is not the latest one. I've tested with --debug output and following is picked: 

	07:49:36.947 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/home/pb/.m2/repository/p6spy/p6spy/3.0.0-SNAPSHOT/p6spy-3.0.0-SNAPSHOT.jar
	07:49:36.947 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'p6spy:p6spy:3.0.0-SNAPSHOT' in repository 'MavenLocal'.
	07:49:36.951 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found cached version of changing module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven2'
	07:49:36.951 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven2'
	07:49:36.952 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found cached version of changing module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven5'
	07:49:36.952 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven5'
	07:49:36.952 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Using p6spy:p6spy:3.0.0-rc2 from Maven repository 'MavenRepo'

So I just gave it a try and changed in the pom.xml to: `3.0.0-rc3-SNAPSHOT` and guess what, it worked (even without any modifications in the `build.gradle` file in the p6spy-it)!
Using `--debug` flag in integration tests  shows:

	07:54:32.221 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.DefaultExternalResourceArtifactResolver] Loading file:/home/pb/.m2/repository/p6spy/p6spy/3.0.0-rc3-SNAPSHOT/p6spy-3.0.0-rc3-SNAPSHOT.jar
	07:54:32.221 [DEBUG] [org.gradle.api.internal.artifacts.repositories.resolver.ExternalResourceResolver] Metadata file found for module 'p6spy:p6spy:3.0.0-rc3-SNAPSHOT' in repository 'MavenLocal'.
	07:54:32.222 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found cached version of changing module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven2'
	07:54:32.223 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven2'
	07:54:32.223 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Found cached version of changing module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven5'
	07:54:32.223 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Using cached module metadata for module 'p6spy:p6spy:2.1.5-SNAPSHOT' in 'maven5'
	07:54:32.223 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.DynamicVersionResolver] Using p6spy:p6spy:3.0.0-rc3-SNAPSHOT from Maven repository 'MavenLocal'

So my suggestion would be to:

1. merge this change, to solve the tomcat issue and keep stuff lazy
1. change p6spy version to: `3.0.0-rc3-SNAPSHOT`
1. re-discuss the pull request https://github.com/p6spy/p6spy-it/pull/19 (maybe in the pull request itself)

**Pull request merged**
