### PR TITLE
#329 - Use default naming policy for CGLIB generated proxies

### PR DESCRIPTION
**Pull request by quintonm**

### CODE REVIEW

**Comment by felixbarny** [comment]
LVGTM

Release time?

**Comment by quintonm** [comment]
@felixbarny Can you verify that the upgrade to CGLIB fixes the deadlock problem that you ran into?

**Comment by felixbarny** [comment]
I already did. It fixes the issue.

**Comment by quintonm** [comment]
Perfect!  I will likely release this evening.

**Pull request merged**
