### PR TITLE
feat: introduced CompoundJdbcEventListener.onAfterStatementClose()

### LINKED ISSUE #376: Event on closing statement
I'm trying to track count of active statements but I didn't find an event after Statement / PreparedStatement / CallableStatement is closed.
Does it makes sence to add `onAfterStatementClose`?

### PR DESCRIPTION
**Pull request by typekpb**
fixes #376

### CODE REVIEW

**Comment by felixbarny** [comment]
Looks nice and clean. Maybe add a simple test?

**Comment by typekpb** [comment]
@felixbarny thanks, will do

**Comment by typekpb** [comment]
anyone ready to merge it, or should I do it?

**Comment by quintonm** [comment]
Any idea what happened to the build? I don't see how this PR could have broken it.

**Comment by typekpb** [comment]
@quintonm for the broken build, see the fix provided: #383, it's temporary, but works. Regarding long term fix, I play with docker and will provide additional PR with intrastructure updates (removing no so popular any more: vagrant, as well as hacks for installing other DBs).

**Pull request merged**
