### PR TITLE
"exludebinary" typo

### PR DESCRIPTION
**Pull request by jorgheymans**

### CODE REVIEW

**Comment by typekpb** [comment]
LGTM

**Comment by typekpb** [comment]
@jorgheymans nice catch, thanks!

**Comment by jorgheymans** [comment]
no problem, are you planning for a 3.1 ? It's a nice feature to have as
part of the brave-p6spy integration.

**Comment by typekpb** [comment]
@quintonm any chance for 3.1 release any time soon?

**Comment by jorgheymans** [comment]
@typekpb @quintonm so how about this release ? What needs to be done to get this out, anything I can do to help ?

**Comment by typekpb** [comment]
My secret hope is to have it done with gradle, so merging related PR would
be a precondition

**Comment by jorgheymans** [comment]
👍  whatever needed to get releases going more frequently

**Comment by typekpb** [comment]
@jorgheymans 3.1.0 version has been released (available in bintray), we wait for maven central sync to happen

**Comment by jorgheymans** [comment]
great stuff, thanks :1st_place_medal:

**Comment by jorgheymans** [comment]
@typekpb are you sure the sync to maven central is automatic ? It's still not there.

**Pull request merged**
