### PR TITLE
[RFC] Gradle introduced

### PR DESCRIPTION
**Pull request by typekpb**
The idea is to let gradle do whatever maven does for us currently:
- [X] green tests (for misc DBs on travis/~~vagrant~~/docker-compose as well as H2 for local tests) 
- [X] license autoadded to file headers (via: `./gradlew licenseFormatMain licenseFormatTest`). moreover presence tested on travis (as part of `./gradlew check`
- [X] snapshot jars pushed to maven repo ( http://oss.jfrog.org/oss-snapshot-local/p6spy/p6spy/ )
- [ ] release jars pushed to maven repo (over bintray)
- [X] coveralls publishing 
~~- [ ] vagrant env setup (for local travis like env)~~
- [X] docker-compose setup (for local travis like env, as well as for the travis, where feasible)
- [X] dev docs updated (mvn -> gradle)
- [X] p6spy*-nodep publishing
- [X] github release notes synced with our docs in `releasenotes.md` via [chandler](https://github.com/mattbrictson/chandler)

btw: this should be a solution to: #292 and #372

### CODE REVIEW

**Comment by typekpb** [comment]
I'd need some help here (for SNAPSHOT publishing), I see 2 possible ways:
* follow http://central.sonatype.org/pages/gradle.html - seems more compicated, encrypting signing files required: private keys file (however it seems, it's possible, see: https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci)
* publish to bintray using: https://github.com/bintray/gradle-bintray-plugin (preferred to travis specific bintray deployment: https://docs.travis-ci.com/user/deployment/bintray/ , as dynamic version numbers are much easier to compute in gradle script than some descriptor.json file)

So my suggestion would be to take 2.nd option and create new SNAPSHOT repo in bintray and try to synchronize to maven repo from there (as we do for releases currently) 
@felixbarny @quintonm is that possible? Or can we serve only releases over bintray?

**Comment by felixbarny** [comment]
Makes sense to have snapshots at bintray as well. For snapshots I don't think its necessary to sync them to the sonatype snapshot repo.

**Comment by typekpb** [comment]
volunteers for creating repo in bintray and providing me with coordinates? or is it created somehow on 1.st publish?

**Comment by typekpb** [comment]
OK, need to figure out waiting for oracle DB to start (as docker healthcheck cmd seems to be failing currently), hope to see the progress today evening

**Comment by typekpb** [comment]
OK, so I've tested releasing SNAPSHOTs to http://oss.jfrog.org/oss-snapshot-local/p6spy/p6spy/ and it works fine (thanks to bintray credentials liked with oss.jfrog.org)

Last open point is releasing non-SNAPSHOT versions via gradle (just by creating a new release using github website), but this can be probably tested only once we merge this a release the next version.

@felixbarny @quintonm I'd love to merge this one, any objections?

**Comment by felixbarny** [comment]
I'm sorry, but I just don't have the time atm to review. But I'd say go for it and try it out.

**Pull request merged**
