### PR TITLE
Always instrument getResultSet

### PR DESCRIPTION
**Pull request by felixbarny**
Previously it was only considered for CallableStatements

Also removed a lot of code duplication

Additionally fixed inconsistency in where executeBatch sometimes
was Category.STATEMENT instead of BATCH

### CODE REVIEW

**Comment by felixbarny** [comment]
I accidentally pushed this to master. Reverted the push with:
```
git reset --hard HEAD~ 
git push -f
```

Sorry for that :(

**Comment by felixbarny** [comment]
Looking forward to reviews so we can release 2.2.1 soon 👍

**Comment by quintonm** [comment]
Good catch only only instrumenting getResultSet on CallableStatement.  For the others, it was only instrumented when calling the execute* methods.

**Comment by quintonm** [comment]
I have no objections to merging this PR.  I like the additional code reuse provided by the inheritance between statement, preparedstatement, and callablestatement.  That is something that I had meant to go back and refactor but never got around to actually doing.

**Comment by typekpb** [comment]
@felixbarny @quintonm LGTM

**Comment by typekpb** [comment]
@felixbarny bad news, sounds like a merge conflict, you might need to update to baseline :(

**Comment by felixbarny** [comment]
No problem. I'll do that tomorrow at work.

**Comment by felixbarny** [comment]
Done. Btw do you get notifications when I add a commit to a pull request?

**Comment by typekpb** [comment]
> Done. 

perfect

> Btw do you get notifications when I add a commit to a pull request?

well, I don't

**Comment by felixbarny** [comment]
Awesome! Seems like nothing stands in the way of 2.2.1?

**Comment by typekpb** [comment]
any chance for #311 ?

**Pull request merged**
